<a href="https://colab.research.google.com/github/arobi-coder/Developing--with-Python/blob/main/Home_Work_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
number = np.array([1,2,3,4,5,6,7])
mult_num = number * 3
print("Multiplication of number:",mult_num)
print("Mean of multiplication number:",mult_num.mean())
print("Maximum:",mult_num.max())

Multiplication of number: [ 3  6  9 12 15 18 21]
Mean of multiplication number: 12.0
Maximum: 21


In [ ]:
arr =np.array([[30,10],[20,40]])
print("Number of Dimensions:",arr.ndim)
print("Mean:",arr.mean())
print("Transpose:\n",arr.T)
print("Sorted along rows:\n",np.sort(arr))
print("Elements greater than 25 :",arr[arr>25])
print("Dot product:\n",np.dot(arr,arr.T))

Number of Dimensions: 2
Mean: 25.0
Transpose:
 [[30 20]
 [10 40]]
Sorted along rows:
 [[10 30]
 [20 40]]
Elements greater than 25 : [30 40]
Dot product:
 [[1000 1000]
 [1000 2000]]
